modLoader = "javafml"
loaderVersion = "[61,)"
issueTrackerURL = "https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues"
license = "All Rights Reserved"

[[mods]]
modId = "biomeswevegone"
version = "${version}"
displayName = "Oh The Biomes We've Gone"
logoFile = "bwg.png"
authors = "Joseph T. McQuigg (JT122406), AOCAWOL, YaBoiChips, Corgi Taco"
description = '''
Sequel to Oh The Biomes You'll Go, this mod adds a variety of new biomes to the game.
'''
displayURL="https://potionstudios.net/"

[[dependencies.biomeswevegone]]
modId = "forge"
mandatory = true
versionRange = "[61.0.3.,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "terrablender"
mandatory = true
versionRange = "[21.11.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "ohthetreesyoullgrow"
mandatory = true
versionRange = "[10.1.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.biomeswevegone]]
modId = "geckolib"
mandatory = true
versionRange = "[5.4.4,)"
ordering = "AFTER"
side = "BOTH"
