org.gradle.jvmargs=-Xmx4G
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=1.21.11

archives_base_name=Oh-The-Biomes-Weve-Gone
mod_version=4.3.1
maven_group=net.potionstudios

fabric_loader_version=0.18.4
fabric_api_version=0.141.3

forge_version=61.0.8

neoforge_version=21.11.38-beta

parchment=2025.12.20

devauth_version=1.2.2

terrablender_version=21.11.0.0
geckolib_version=5.4.3
corgilib_version=9.0.0.0
ohthetreesyoullgrow_version=9.0.0

WTHIT=18.2.1
badPackets=0.11.2