org.gradle.jvmargs=-Xmx4G
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=26.1.2

archives_base_name=Oh-The-Biomes-Weve-Gone
mod_version=5.0.0-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.19.3
fabric_api_version=0.152.1

forge_version=64.0.9

neoforge_version=26.1.2.76

devauth_version=1.2.2

terrablender_version=26.1.2.0.2
geckolib_version=5.5.1
ohthetreesyoullgrow_version=10.1.1

WTHIT=19.0.1
badPackets=0.12.2