org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.10

archives_base_name=Oh-The-Biomes-Weve-Gone
mod_version=4.2.1-SNAPSHOT
maven_group=net.potionstudios

fabric_loader_version=0.18.3
fabric_api_version=0.138.3

forge_version=60.1.5

neoforge_version=21.10.64

parchment=2025.10.12

devauth_version=1.2.1

terrablender_version=21.10.0.0
geckolib_version=5.3-alpha-3
corgilib_version=8.0.0.0
ohthetreesyoullgrow_version=8.0.2

WTHIT=17.3.4
badPackets=0.10.2